services:
  postgresql:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pgpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "db_prod" ]
      interval: 5s
      timeout: 60s
      retries: 20
      start_period: 20s
  backend:
    build:
      context: ..
      dockerfile: src/main/docker/Dockerfile.native
    command: "
    -Dquarkus.datasource.db-kind=postgresql \
    -Dquarkus.datasource.username=postgres \
    -Dquarkus.datasource.password=pgpass \
    -Dquarkus.datasource.jdbc.url=jdbc:postgresql://postgresql:5432/postgres \
    -Dquarkus.hibernate-orm.database.generation=drop-and-create
    "
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy